cache_config:
  cache: False
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: null

feedback: False

model_config:
  open_ai_key: null
  model: huggingface_model
  model_name: psmathur/orca_mini_3b
  max_tokens: 2500

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
