cache_config:
  cache: True
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: https://www.dropbox.com/scl/fi/tpyl4hcrti63vvy0v6wm4/NMA_2023_v0.1.cache?rlkey=w5orop5qvmsl1u3hi96xtv5fu&dl=1

feedback: False

model_config:
  open_ai_key: null
  model: cached_model
  model_name: gpt-3.5-turbo # text-curie-001

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
