cache_config:
  cache: True
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: https://www.dropbox.com/scl/fi/me6j23a942uq1f278msv4/NMA_2023_CN_DL_v0.1.cache?rlkey=kv1m1ho5sz30ac7eoylov6b3i&dl=1

feedback: False

model_config:
  open_ai_key: null
  model: cached_model
  model_name: gpt-3.5-turbo # text-curie-001

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
