cache_config:
  cache: False
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: null

feedback: False

model_config:
  open_ai_key: null
  model: llama_model
  model_name: TheBloke/Llama-2-7B-Chat-GGML
  weights_fname: llama-2-7b-chat.ggmlv3.q5_1.bin
  max_tokens: 1024
  n_gpu_layers: 40
  n_batch: 512

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor, tester, inventer, experimenter]
