cache_config:
  cache: True
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: https://www.dropbox.com/scl/fi/gikfgfag1ya44ph619x77/NMA_2023_v0.1_pickle.cache?rlkey=a989au3ilo6uvixp9avcmsc2m&dl=1

feedback: False

model_config:
  open_ai_key: null
  model: fake_model
  model_name: gpt-3.5-turbo # text-curie-001

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
