cache_config:
  cache: False
  caching_strategy: exact # or similarity
  cache_db_version: 0.1
  url: null

feedback: False

model_config:
  open_ai_key: null
  model: huggingface_model
  model_name: meta-llama/Llama-2-7b  # for better answers use Llama-2-70b (requires more disk space than Colab free provides)
  max_tokens: 2500

chain_config:
  chain_type: default

prompts_config:
  prompts_to_use: [tutor]
